# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('sex', models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=1)),
                ('birtday', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type_account', models.CharField(choices=[('1', 'Admin'), ('2', 'Author'), ('3', 'Manager'), ('4', 'Staff')], default=4, max_length=1)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('active', models.CharField(choices=[('1', 'True'), ('0', 'False')], default=0, max_length=1)),
                ('key', models.TextField()),
                ('online', models.BooleanField(default=False)),
                ('avatar', models.ImageField(upload_to='upload/avatar/')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unsigned_name', models.CharField(max_length=200)),
                ('order_sort', models.IntegerField()),
                ('public', models.CharField(choices=[('1', 'True'), ('0', 'False')], default=0, max_length=1)),
                ('meta_desc', models.CharField(max_length=120)),
                ('meta_key', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('unsigned_title', models.CharField(max_length=250)),
                ('excerpt', models.TextField()),
                ('image', models.ImageField(upload_to='upload/post/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('pre_post', models.IntegerField()),
                ('next_post', models.IntegerField()),
                ('highlight', models.CharField(choices=[('1', 'True'), ('0', 'False')], default=0, max_length=1)),
                ('public', models.CharField(choices=[('1', 'Public'), ('0', 'Private')], default=1, max_length=1)),
                ('id_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('unsigned_name', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='blog.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts'),
        ),
    ]
