# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='public',
            field=models.FileField(choices=[('1', 'True'), ('0', 'False')], default=1, max_length=1, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
