# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170714_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Posts', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Catalog', verbose_name='Catalog'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Account', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='next_post',
            field=models.IntegerField(verbose_name='Next Post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pre_post',
            field=models.IntegerField(verbose_name='Preview Post'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='view',
            field=models.IntegerField(default=0, verbose_name='View'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='unsigned_name',
            field=models.CharField(max_length=200),
        ),
    ]
